Increase/Decrease volume by 5
hrkfdn/ncspot pull request #298
Opened 2020-10-20 20:59 UTC by ChaboCode

2020-10-21 07:44 UTC, hrkfdn requested changes
Thanks for the PR. There is one problem with the parsing of custom `volume N` bindings where `N` is basically ignored and a static value of `1` is used for the amount. Could you please adapt this?

2020-10-21 07:44 UTC, hrkfdn commented on src/command.rs
> +        "voldown" => Some(Command::VolumeDown(1)),
This will always use `1` for the amount when parsing the bindings

2020-10-21 16:28 UTC, ChaboCode commented
Can you label this `hacktoberfest-accepted` please?

2020-10-22 18:21 UTC, merged

2020-10-22 18:24 UTC, hrkfdn commented
Merged, thanks.