Improved `seek` command to allow more units
hrkfdn/ncspot pull request #682
Opened 2021-12-26 20:48 UTC by cyqsimon

I changed the `seek` command to use [parse_duration](https://docs.rs/parse_duration/latest/parse_duration/), so now it accepts not only milliseconds as input but also more convenient units (mix and match capability included). I think this is a good quality-of-life improvement.

![new_seek](https://user-images.githubusercontent.com/28627918/147419665-67d8de01-80c4-41ee-a507-69d38842970b.gif)

2021-12-26 21:32 UTC, hrkfdn requested changes
Thank you, love the idea! Could you fix the formatting using `cargo fmt`? Then I'll happily merge it.

2021-12-27 04:06 UTC, cyqsimon commented
Oh oops. I have a custom global `rustfmt.toml` so that screwed things up. Sorted.

Should I also commit an empty `rustfmt.toml` so that this doesn't happen again for others?

2021-12-27 08:28 UTC, hrkfdn commented
> Should I also commit an empty `rustfmt.toml` so that this doesn't happen again for others?

Ah, it only uses the default values if the project has an empty config? Thanks for the hint, I'll create one after merging this PR.

2021-12-27 08:28 UTC, merged

2021-12-27 08:46 UTC, cyqsimon commented
> > Should I also commit an empty `rustfmt.toml` so that this doesn't happen again for others?
> 
> Ah, it only uses the default values if the project has an empty config? Thanks for the hint, I'll create one after merging this PR.

I believe so. See https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#configuring-rustfmt

Says here that global configs are only sourced if no config file is found in project.